name: turt
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  flutter_modular: ^1.2.5+1
  cupertino_icons: ^0.1.3
  logic:
    path: './logic'
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true